---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    name: Build and Test Kotlin
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # should be cached
          java-version: '17'
          cache: 'gradle'
      - name: Build & Test
        run: cd kotlin && ./gradlew build --no-daemon
...
